version: '3.4'
services:
  word-processor-server:
    image: syncfusion/word-processor-server:latest
    environment:
      SYNCFUSION_LICENSE_KEY: ${NEXT_PUBLIC_SYNCFUSION_KEY}
    volumes:
      - ./data:/app/data
    ports:
      - '6002:80'
